# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aOHU4zUMEsst8J155hNItbXQgHRy8AoRUdWdIgptmIAWwvVI2frt4nLLIcCQMT+jD1IoqipBvBXdR1zqspSWcbY+f3Lx4WFBIWHzPAmB5RTSh3SpnqmhDrzPeoD6ypqwwT/agGBR/7DkrhasebX/4SzqI8UAoEZDwKu08X+q4b6a9WJEBweKPEgYqXlNw7p4qQapx5b+mPvg80+Kd9WgYbXczDax/nIl1yn7pidbYZhA44azFxs/x+fI9AbY/DY54ujujp89LJiw+UGyarQepzWTfZ98DICAQWlQfsk6JxxReKthH/l/kPhG6mBgCFRhz8WOL/pes3jwYrNL+9623NiA6cEv6w5EGBsDQzwI89AE5WaMh78byCG9IsOTrrA8mfwNVbGNAXJ/lu0vuqRlkyaBzzTDNgE/Ihcrktj0gdqfhFyW65h+wBG7dBKz5AkvS5MPehsWF7xpC8F4P7vqGzOf0weWIF32jXGo8Yqq5r5rDnNZepWjJ2bs7Pk2Ue+Rl13rvmOS/oDqg4+7gIe39fRckX2bkMq4nwjO57nh6jhhbozzBwB10IEwi62cWRxqof6PILblA9ZJJX9s7owsppRX5rh0cftTdiZo8+IXqbUji/GovTcG+pFW+MVXTnJx+AZ0o67L567RQ1trP92e209j3kYmoPQVtqFTOnI/oN4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
