# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cz5C+mP0nBNgL8oOhEKE0HptxgSl02soq61JDWkiogNLgb6LaEUCR8rbZGsGpW7crbApgOUBqHL0bi/dyt5CiUET6+pTZJJYBlXHAWHSaE7he/Nf1kRBS3csVPcwxLbNRpCZQZFRgRzs6F0HoGunAm2SH4lJ1GrGu/8PmjPZ/dOhf/Ek9E+Tkax/8gbAlrVjWBtcQI9HqoXe3H+3oyh/8C7Kcb/foN9mOC9W6lwJlP7/rUz/QNbJ0449I3YCsvI5m3K2xQBn/nT8ootNzzm1XjuI43pndWdnHUecSNSMLMNMkw4zSr0WDHTxSpvEZgNez0puOyeRcMWFTesT4kdnufzKRpEJl6Dpc6i5hINvIXUHA+ur/kizlOhMZbJ1RBiBW9S6/SabgI/T2RG68o3t6oOI8VIDD6jCvNRclHbb4QaRYP3adoqTue/mltQ1wTh+kpVwWW93tleDcdj1o4xz4B4KpFz0SWcpcJzgrZPnzKGu3FEX79yt7SyRoAm2Iqzawwr/QLDFWAq34fOiksUrr0sreT855cknkpfgQalUslOQFM1FODDjylW6F1kPter75Z69Akx9T+sRc9mFd+kzwZ8VNAcjfSPrZKPHSUT6bNP9375fQlHs9zo7KDGv0tGG+gRiFtOwRC2eZYeL1Exa24tXCTkCJCHeRkLTypjwqv8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
