travis:
  secure:
    BINSTAR_TOKEN: aOHU4zUMEsst8J155hNItbXQgHRy8AoRUdWdIgptmIAWwvVI2frt4nLLIcCQMT+jD1IoqipBvBXdR1zqspSWcbY+f3Lx4WFBIWHzPAmB5RTSh3SpnqmhDrzPeoD6ypqwwT/agGBR/7DkrhasebX/4SzqI8UAoEZDwKu08X+q4b6a9WJEBweKPEgYqXlNw7p4qQapx5b+mPvg80+Kd9WgYbXczDax/nIl1yn7pidbYZhA44azFxs/x+fI9AbY/DY54ujujp89LJiw+UGyarQepzWTfZ98DICAQWlQfsk6JxxReKthH/l/kPhG6mBgCFRhz8WOL/pes3jwYrNL+9623NiA6cEv6w5EGBsDQzwI89AE5WaMh78byCG9IsOTrrA8mfwNVbGNAXJ/lu0vuqRlkyaBzzTDNgE/Ihcrktj0gdqfhFyW65h+wBG7dBKz5AkvS5MPehsWF7xpC8F4P7vqGzOf0weWIF32jXGo8Yqq5r5rDnNZepWjJ2bs7Pk2Ue+Rl13rvmOS/oDqg4+7gIe39fRckX2bkMq4nwjO57nh6jhhbozzBwB10IEwi62cWRxqof6PILblA9ZJJX9s7owsppRX5rh0cftTdiZo8+IXqbUji/GovTcG+pFW+MVXTnJx+AZ0o67L567RQ1trP92e209j3kYmoPQVtqFTOnI/oN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
