travis:
  secure:
    BINSTAR_TOKEN: cz5C+mP0nBNgL8oOhEKE0HptxgSl02soq61JDWkiogNLgb6LaEUCR8rbZGsGpW7crbApgOUBqHL0bi/dyt5CiUET6+pTZJJYBlXHAWHSaE7he/Nf1kRBS3csVPcwxLbNRpCZQZFRgRzs6F0HoGunAm2SH4lJ1GrGu/8PmjPZ/dOhf/Ek9E+Tkax/8gbAlrVjWBtcQI9HqoXe3H+3oyh/8C7Kcb/foN9mOC9W6lwJlP7/rUz/QNbJ0449I3YCsvI5m3K2xQBn/nT8ootNzzm1XjuI43pndWdnHUecSNSMLMNMkw4zSr0WDHTxSpvEZgNez0puOyeRcMWFTesT4kdnufzKRpEJl6Dpc6i5hINvIXUHA+ur/kizlOhMZbJ1RBiBW9S6/SabgI/T2RG68o3t6oOI8VIDD6jCvNRclHbb4QaRYP3adoqTue/mltQ1wTh+kpVwWW93tleDcdj1o4xz4B4KpFz0SWcpcJzgrZPnzKGu3FEX79yt7SyRoAm2Iqzawwr/QLDFWAq34fOiksUrr0sreT855cknkpfgQalUslOQFM1FODDjylW6F1kPter75Z69Akx9T+sRc9mFd+kzwZ8VNAcjfSPrZKPHSUT6bNP9375fQlHs9zo7KDGv0tGG+gRiFtOwRC2eZYeL1Exa24tXCTkCJCHeRkLTypjwqv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
